// Lớp hỗ trợ cung cấp dữ liệu bản đồ địa chỉ hành chính (Tỉnh/Thành phố -> Quận/Huyện -> Phường/Xã) của Việt Nam
class DiaChiHelper {
  DiaChiHelper._();

  static const Map<String, Map<String, List<String>>> mapDiaChi = {
    "Thành phố Hà Nội": {
      "Quận Hoàn Kiếm": ["Phường Hoàn Kiếm", "Phường Cửa Nam"],
      "Quận Ba Đình": ["Phường Điện Biên", "Phường Quán Thánh", "Phường Ngọc Hà", "Phường Kim Mã", "Phường Giảng Võ"],
      "Quận Đống Đa": ["Phường Đống Đa", "Phường Láng", "Phường Ô Chợ Dừa", "Phường Kim Liên", "Phường Văn Miếu - Quốc Tử Giám"],
      "Quận Thanh Xuân": ["Phường Thanh Xuân", "Phường Khương Đình", "Phường Phương Liệt"],
      "Quận Cầu Giấy": ["Phường Cầu Giấy", "Phường Nghĩa Đô", "Phường Yên Hòa"],
    },
    "Thành phố Hồ Chí Minh": {
      "Quận 1": ["Phường Sài Gòn", "Phường Tân Định", "Phường Bến Thành", "Phường Cầu Ông Lãnh"],
      "Quận 3": ["Phường Bàn Cờ", "Phường Xuân Hòa", "Phường Nhiêu Lộc"],
      "Thành phố Thủ Đức": ["Phường Thảo Điền", "Phường An Phú", "Phường Bình Thọ", "Phường Hiệp Bình Chánh", "Phường Linh Trung"],
      "Thành phố Thủ Dầu Một": ["Phường Phú Cường", "Phường Hiệp Thành", "Phường Chánh Nghĩa", "Phường Phú Hòa"],
      "Thành phố Vũng Tàu": ["Phường 1", "Phường 2", "Phường Thắng Tam", "Phường Thắng Nhì", "Phường Rạch Dừa"],
    },
    "Thành phố Hải Phòng": {
      "Quận Hồng Bàng": ["Phường Hồng Bàng", "Phường Hồng An"],
      "Quận Lê Chân": ["Phường Lê Chân", "Phường An Biên"],
      "Thành phố Hải Dương": ["Phường Quang Trung", "Phường Trần Hưng Đạo", "Phường Hải Tân", "Phường Bình Hàn"],
      "Thị xã Chí Linh": ["Phường Sao Đỏ", "Phường Phả Lại", "Phường Bến Tắm"],
      "Huyện Thủy Nguyên": ["Thị trấn Núi Đèo", "Xã Quảng Thanh", "Xã Minh Tân"],
    },
    "Thành phố Đà Nẵng": {
      "Quận Hải Châu": ["Phường Hải Châu", "Phường Hòa Cường"],
      "Quận Thanh Khê": ["Phường Thanh Khê", "Phường An Khê"],
      "Quận Sơn Trà": ["Phường An Hải", "Phường Sơn Trà"],
      "Thành phố Tam Kỳ": ["Phường An Mỹ", "Phường Tân Thạnh", "Phường Hòa Hương", "Phường Phước Hòa"],
      "Thành phố Hội An": ["Phường Minh An", "Phường Cẩm Phô", "Phường Sơn Phong", "Phường Tân An"],
      "Huyện Hòa Vang": ["Xã Hòa Tiến", "Xã Hòa Phong", "Xã Hòa Châu"],
    },
    "Thành phố Huế": {
      "Quận Phú Xuân": ["Phường Phú Xuân", "Phường Vỹ Dạ", "Phường Thuận An", "Phường Hóa Châu", "Phường Mỹ Thượng", "Phường Phong Điền", "Phường Phong Thái", "Phường Phong Dinh"],
      "Quận Thuận Hóa": ["Phường Thuận Hóa", "Phường Kim Long", "Phường Hương An", "Phường An Cựu", "Phường Thủy Xuân", "Phường Thanh Thủy", "Phường Hương Thủy"],
      "Thị xã Hương Thủy": ["Phường Phú Bài", "Phường Thủy Lương", "Phường Thủy Phương", "Phường Thủy Châu"],
      "Thị xã Hương Trà": ["Phường Hương Trà", "Phường Kim Trà", "Phường Hương Xuân", "Phường Hương Chữ"],
    },
    "Thành phố Cần Thơ": {
      "Quận Ninh Kiều": ["Phường Ninh Kiều", "Phường Cái Khế", "Phường Tân An", "Phường An Bình"],
      "Quận Cái Răng": ["Phường Lê Bình", "Phường Hưng Phú", "Phường Ba Láng"],
      "Thành phố Sóc Trăng": ["Phường 1", "Phường 2", "Phường 3", "Phường 4", "Phường 5"],
      "Thành phố Vị Thanh": ["Phường 1", "Phường 3", "Phường 4", "Phường 5"],
    },
    "Tỉnh Lai Châu": {
      "Thành phố Lai Châu": ["Phường Quyết Thắng", "Phường Đông Phong", "Phường Tân Phong", "Phường Đoàn Kết"],
      "Huyện Phong Thổ": ["Thị trấn Phong Thổ", "Xã Mường So", "Xã Khổng Lào"],
    },
    "Tỉnh Điện Biên": {
      "Thành phố Điện Biên Phủ": ["Phường Mường Thanh", "Phường Thanh Trường", "Phường Nam Thanh", "Phường Tân Thanh"],
      "Huyện Điện Biên Đông": ["Thị trấn Điện Biên Đông", "Xã Mường Luân", "Xã Na Son"],
    },
    "Tỉnh Sơn La": {
      "Thành phố Sơn La": ["Phường Chiềng Lề", "Phường Quyết Thắng", "Phường Tô Hiệu", "Phường Chiềng An"],
      "Huyện Mộc Châu": ["Thị trấn Mộc Châu", "Thị trấn Nông trường Mộc Châu", "Xã Đông Sang"],
    },
    "Tỉnh Lạng Sơn": {
      "Thành phố Lạng Sơn": ["Phường Chi Lăng", "Phường Tam Thanh", "Phường Hoàng Văn Thụ", "Phường Vĩnh Trại"],
      "Huyện Cao Lộc": ["Thị trấn Cao Lộc", "Thị trấn Đồng Đăng", "Xã Hợp Thành"],
    },
    "Tỉnh Quảng Ninh": {
      "Thành phố Hạ Long": ["Phường Hồng Gai", "Phường Bãi Cháy", "Phường Cao Xanh", "Phường Giếng Đáy", "Phường Hồng Hà"],
      "Thành phố Cẩm Phả": ["Phường Cẩm Trung", "Phường Cẩm Thành", "Phường Cẩm Tây", "Phường Cẩm Thủy"],
      "Thành phố Móng Cái": ["Phường Trần Phú", "Phường Ka Long", "Phường Hòa Lạc"],
      "Huyện Vân Đồn": ["Thị trấn Cái Rồng", "Xã Hạ Long", "Xã Đông Xá"],
    },
    "Tỉnh Thanh Hóa": {
      "Thành phố Thanh Hóa": ["Phường Điện Biên", "Phường Ba Đình", "Phường Lam Sơn", "Phường Đông Thọ", "Phường Quảng Thắng"],
      "Thành phố Sầm Sơn": ["Phường Trường Sơn", "Phường Bắc Sơn", "Phường Trung Sơn"],
      "Thị xã Bỉm Sơn": ["Phường Ngọc Trạo", "Phường Ba Đình", "Phường Lam Sơn"],
      "Huyện Quảng Xương": ["Thị trấn Tân Phong", "Xã Quảng Yên", "Xã Quảng Hòa"],
    },
    "Tỉnh Nghệ An": {
      "Thành phố Vinh": ["Phường Bến Thủy", "Phường Hưng Dũng", "Phường Lê Mao", "Phường Quang Trung", "Phường Trường Thi"],
      "Thị xã Cửa Lò": ["Phường Nghi Thu", "Phường Thu Thủy", "Phường Nghi Hương"],
      "Huyện Nam Đàn": ["Thị trấn Nam Đàn", "Xã Kim Liên", "Xã Nam Giang"],
    },
    "Tỉnh Hà Tĩnh": {
      "Thành phố Hà Tĩnh": ["Phường Trần Phú", "Phường Nam Hà", "Phường Nguyễn Du", "Phường Đại Nài"],
      "Thị xã Kỳ Anh": ["Phường Sông Trí", "Phường Kỳ Liên", "Phường Kỳ Long"],
      "Huyện Nghi Xuân": ["Thị trấn Tiên Điền", "Xã Xuân Giang", "Xã Xuân Hải"],
    },
    "Tỉnh Cao Bằng": {
      "Thành phố Cao Bằng": ["Phường Hợp Giang", "Phường Sông Hiến", "Phường Tân Giang", "Phường Đề Thám"],
      "Huyện Bảo Lâm": ["Thị trấn Pác Miầu", "Xã Mông Ân", "Xã Thái Học"],
      "Huyện Quảng Hòa": ["Thị trấn Quảng Uyên", "Xã Hạnh Phúc", "Xã Chí Thảo"],
    },
    "Tỉnh Lào Cai": {
      "Thành phố Lào Cai": ["Phường Cốc Lếu", "Phường Kim Tân", "Phường Bắc Cường", "Phường Pom Hán", "Phường Nam Cường"],
      "Huyện Sa Pa": ["Thị trấn Sa Pa", "Xã Lao Chải", "Xã Tả Van", "Xã Tả Phìn"],
      "Thành phố Yên Bái": ["Phường Hồng Hà", "Phường Nguyễn Thái Học", "Phường Yên Thịnh", "Phường Đồng Tâm", "Phường Minh Tân"],
      "Thị xã Sa Pa": ["Phường Sa Pa", "Phường Hàm Rồng", "Phường Cầu Mây"],
      "Huyện Văn Chấn": ["Thị trấn Sơn Thịnh", "Thị trấn Trần Phú", "Xã Tú Lệ"],
      "Huyện Mù Cang Chải": ["Thị trấn Mù Cang Chải", "Xã Cao Phạ", "Xã Púng Luông"],
    },
    "Tỉnh Yên Bái": {
      "Thành phố Yên Bái": ["Phường Đồng Tâm", "Phường Minh Tân", "Phường Nguyễn Thái Học", "Phường Yên Thịnh"],
      "Huyện Mù Cang Chải": ["Thị trấn Mù Cang Chải", "Xã Cao Phạ", "Xã Púng Luông"],
    },
    "Tỉnh Tuyên Quang": {
      "Phường Minh Xuân": ["Phường Minh Xuân"],
      "Phường Tân Quang": ["Phường Tân Quang"],
      "Phường Phan Thiết": ["Phường Phan Thiết"],
      "Phường Nông Tiến": ["Phường Nông Tiến"],
      "Thành phố Tuyên Quang": ["Phường Tân Quang", "Phường Minh Xuân", "Phường Phan Thiết", "Phường Ỷ La"],
      "Thành phố Hà Giang": ["Phường Trần Phú", "Phường Minh Khai", "Phường Nguyễn Trãi", "Phường Quang Trung"],
      "Huyện Hàm Yên": ["Thị trấn Tân Yên", "Xã Thái Hòa", "Xã Đức Ninh"],
      "Huyện Vị Xuyên": ["Thị trấn Vị Xuyên", "Thị trấn Nông trường Việt Lâm", "Xã Đạo Đức"],
      "Huyện Sơn Dương": ["Thị trấn Sơn Dương", "Xã Tân Trào", "Xã Lương Thiện"],
    },
    "Tỉnh Phú Thọ": {
      "Thành phố Việt Trì": ["Phường Gia Cẩm", "Phường Tiên Cát", "Phường Thọ Sơn", "Phường Nông Trang", "Phường Tân Dân", "Phường Bạch Hạc"],
      "Thành phố Vĩnh Yên": ["Phường Liên Bảo", "Phường Tích Sơn", "Phường Đồng Tâm", "Phường Ngô Quyền"],
      "Thành phố Hòa Bình": ["Phường Hữu Nghị", "Phường Phương Lâm", "Phường Tân Thịnh", "Phường Đồng Tiến"],
      "Thị xã Phú Thọ": ["Phường Phong Châu", "Phường Hùng Vương", "Phường Thanh Vinh"],
      "Thị xã Phúc Yên": ["Phường Hùng Vương", "Phường Trưng Trắc", "Phường Đồng Xuân"],
      "Huyện Thanh Sơn": ["Thị trấn Thanh Sơn", "Xã Cự Đồng", "Xã Võ Miếu", "Xã Sơn Hùng", "Xã Địch Quả"],
    },
    "Tỉnh Vĩnh Phúc": {
      "Thành phố Vĩnh Yên": ["Phường Tích Sơn", "Phường Liên Bảo", "Phường Đồng Tâm", "Phường Ngô Quyền"],
      "Huyện Tam Đảo": ["Thị trấn Tam Đảo", "Thị trấn Hợp Châu", "Xã Đại Đình"],
    },
    "Tỉnh Bắc Ninh": {
      "Thành phố Bắc Ninh": ["Phường Suối Hoa", "Phường Tiền An", "Phường Ninh Xá", "Phường Đại Phúc", "Phường Võ Cường"],
      "Thành phố Bắc Giang": ["Phường Ngô Quyền", "Phường Trần Nguyên Hãn", "Phường Hoàng Văn Thụ", "Phường Lê Lợi"],
      "Thị xã Từ Sơn": ["Phường Đông Ngàn", "Phường Đồng Nguyên", "Phường Trang Hạ"],
      "Huyện Việt Yên": ["Thị trấn Bích Động", "Thị trấn Nếnh", "Xã Quang Châu"],
      "Huyện Tiên Du": ["Thị trấn Lim", "Xã Liên Bão", "Xã Phật Tích"],
    },
    "Tỉnh Hải Dương": {
      "Thành phố Hải Dương": ["Phường Quang Trung", "Phường Trần Hưng Đạo", "Phường Ngọc Châu"],
      "Huyện Thanh Hà": ["Thị trấn Thanh Hà", "Xã Thanh Sơn", "Xã Thanh Xá"],
    },
    "Tỉnh Hưng Yên": {
      "Thành phố Hưng Yên": ["Phường Hiến Nam", "Phường Lê Lợi", "Phường Quang Trung", "Phường Lam Sơn"],
      "Thành phố Thái Bình": ["Phường Đề Thám", "Phường Lê Hồng Phong", "Phường Kỳ Bá", "Phường Trần Hưng Đạo"],
      "Huyện Mỹ Hào": ["Phường Bần Yên Nhân", "Phường Nhân Hòa", "Phường Bạch Sam"],
      "Huyện Đông Hưng": ["Thị trấn Đông Hưng", "Xã Đông Hợp", "Xã Đông Động"],
      "Huyện Văn Giang": ["Thị trấn Văn Giang", "Xã Xuân Quan", "Xã Phụng Công"],
    },
    "Tỉnh Thái Bình": {
      "Thành phố Thái Bình": ["Phường Đề Thám", "Phường Lê Hồng Phong", "Phường Kỳ Bá"],
      "Huyện Tiền Hải": ["Thị trấn Tiền Hải", "Xã Đông Lâm", "Xã Tây Giang"],
    },
    "Tỉnh Hà Nam": {
      "Thành phố Phủ Lý": ["Phường Minh Khai", "Phường Hai Bà Trưng", "Phường Liêm Chính"],
      "Huyện Kim Bảng": ["Thị trấn Quế", "Xã Thi Sơn", "Xã Tượng Lĩnh"],
    },
    "Tỉnh Nam Định": {
      "Thành phố Nam Định": ["Phường Vị Xuyên", "Phường Trần Hưng Đạo", "Phường Năng Tĩnh"],
      "Huyện Hải Hậu": ["Thị trấn Yên Định", "Thị trấn Thịnh Long", "Xã Hải Đông"],
    },
    "Tỉnh Ninh Bình": {
      "Thành phố Ninh Bình": ["Phường Vân Giang", "Phường Thanh Bình", "Phường Nam Bình", "Phường Phúc Thành"],
      "Thành phố Phủ Lý": ["Phường Minh Khai", "Phường Hai Bà Trưng", "Phường Trần Hưng Đạo", "Phường Liêm Chính"],
      "Thành phố Nam Định": ["Phường Vị Hoàng", "Phường Trần Hưng Đạo", "Phường Năng Tĩnh", "Phường Cửa Bắc"],
      "Huyện Hoa Lư": ["Thị trấn Thiên Tôn", "Xã Trường Yên", "Xã Ninh Vân", "Xã Ninh Hải", "Xã Ninh Xuân"],
      "Huyện Ý Yên": ["Thị trấn Lâm", "Xã Yên Tiến", "Xã Yên Khánh"],
    },
    "Tỉnh Quảng Bình": {
      "Thành phố Đồng Hới": ["Phường Đồng Mỹ", "Phường Hải Đình", "Phường Nam Lý"],
      "Huyện Lệ Thủy": ["Thị trấn Kiến Giang", "Xã An Thủy", "Xã Phong Thủy"],
    },
    "Tỉnh Quảng Trị": {
      "Thành phố Đông Hà": ["Phường 1", "Phường 2", "Phường 5", "Phường Đông Thanh", "Phường Đông Lương"],
      "Thành phố Đồng Hới": ["Phường Hải Đình", "Phường Đồng Mỹ", "Phường Đồng Sơn", "Phường Bắc Lý"],
      "Thị xã Quảng Trị": ["Phường 1", "Phường 2", "Phường An Đôn"],
      "Huyện Lệ Thủy": ["Thị trấn Kiến Giang", "Xã Phong Thủy", "Xã An Thủy"],
      "Huyện Vĩnh Linh": ["Thị trấn Hồ Xá", "Xã Vĩnh Kim", "Xã Vĩnh Thạch"],
    },
    "Tỉnh Quảng Nam": {
      "Thành phố Tam Kỳ": ["Phường An Xuân", "Phường Phước Hòa", "Phường Hòa Thuận"],
      "Huyện Duy Xuyên": ["Thị trấn Nam Phước", "Xã Duy Sơn", "Xã Duy Trinh"],
    },
    "Tỉnh Quảng Ngãi": {
      "Thành phố Quảng Ngãi": ["Phường Nguyễn Nghiêm", "Phường Trần Hưng Đạo", "Phường Nghĩa Chánh", "Phường Chánh Lộ", "Phường Quảng Phú"],
      "Thành phố Kon Tum": ["Phường Quyết Thắng", "Phường Quang Trung", "Phường Thống Nhất", "Phường Duy Tân"],
      "Huyện Lý Sơn": ["Xã An Vĩnh", "Xã An Hải"],
      "Huyện Bình Sơn": ["Thị trấn Châu Ổ", "Xã Bình Đông", "Xã Bình Thạnh"],
      "Huyện Đắk Hà": ["Thị trấn Đắk Hà", "Xã Hà Mòn", "Xã Đắk La"],
    },
    "Tỉnh Bình Định": {
      "Thành phố Quy Nhơn": ["Phường Trần Phú", "Phường Lê Lợi", "Phường Ngô Mây"],
      "Huyện Tây Sơn": ["Thị trấn Phú Phong", "Xã Tây Giang", "Xã Bình Nghi"],
    },
    "Tỉnh Phú Yên": {
      "Thành phố Tuy Hòa": ["Phường 1", "Phường 5", "Phường Phú Đông"],
      "Huyện Sông Hinh": ["Thị trấn Hai Riêng", "Xã Sơn Giang", "Xã Đức Bình Đông"],
    },
    "Tỉnh Khánh Hòa": {
      "Thành phố Nha Trang": ["Phường Lộc Thọ", "Phường Tân Lập", "Phường Phước Long", "Phường Vĩnh Nguyên", "Phường Vĩnh Hải", "Phường Phước Tiến"],
      "Thành phố Phan Rang - Tháp Chàm": ["Phường Mỹ Hải", "Phường Thanh Sơn", "Phường Phủ Hà", "Phường Kinh Dinh"],
      "Thành phố Cam Ranh": ["Phường Ba Ngòi", "Phường Cam Lộc", "Phường Cam Phú"],
      "Thị xã Ninh Hòa": [
        "Phường Ninh Hiệp",
        "Phường Nam Ninh Hòa",
        "Phường Đông Ninh Hòa",
        "Xã Ninh An",
        "Xã Ninh Thọ",
        "Xã Ninh Vân",
        "Phường Ninh Hòa",
        "Phường Hòa Thắng",
        "Xã Bắc Ninh Hòa",
        "Xã Hòa Trí",
        "Xã Tân Định",
        "Xã Tây Ninh Hòa"
      ],
      "Huyện Vạn Ninh": ["Thị trấn Vạn Giã", "Xã Vạn Thạnh", "Xã Vạn Thắng", "Xã Vạn Khánh"],
      "Huyện Ninh Sơn": ["Thị trấn Tân Sơn", "Xã Quảng Sơn", "Xã Lương Sơn"],
    },
    "Tỉnh Thái Nguyên": {
      "Thành phố Thái Nguyên": ["Phường Phan Đình Phùng", "Phường Quang Trung", "Phường Hoàng Văn Thụ", "Phường Trung Vương"],
      "Thành phố Sông Công": ["Phường Thắng Lợi", "Phường Cải Đan", "Phường Mỏ Chè"],
      "Thành phố Bắc Kạn": ["Phường Phùng Chí Kiên", "Phường Sông Cầu", "Phường Nguyễn Thị Minh Khai"],
      "Huyện Ba Bể": ["Thị trấn Chợ Rã", "Xã Khang Ninh", "Xã Nam Mẫu"],
    },
    "Tỉnh Gia Lai": {
      "Thành phố Pleiku": ["Phường Tây Sơn", "Phường Diên Hồng", "Phường Hoa Lư", "Phường Phù Đổng"],
      "Thành phố Quy Nhơn": ["Phường Lê Lợi", "Phường Nguyễn Văn Cừ", "Phường Ngô Mây", "Phường Ghềnh Ráng"],
      "Thị xã An Nhơn": ["Phường Bình Định", "Phường Đập Đá", "Phường Nhơn Hưng"],
      "Huyện Đắk Đoa": ["Thị trấn Đắk Đoa", "Xã Tân Bình", "Xã Hneng"],
    },
    "Tỉnh Đắk Lắk": {
      "Thành phố Buôn Ma Thuột": ["Phường Thắng Lợi", "Phường Tân Lợi", "Phường Tân An", "Phường Thành Nhất"],
      "Thành phố Tuy Hòa": ["Phường 1", "Phường 5", "Phường Phú Đông", "Phường 8"],
      "Huyện Krông Pắc": ["Thị trấn Phước An", "Xã Ea Yông", "Xã Hòa Đông"],
      "Huyện Sông Hinh": ["Thị trấn Hai Riêng", "Xã Sơn Giang", "Xã Đức Bình Đông"],
    },
    "Tỉnh Lâm Đồng": {
      "Thành phố Đà Lạt": ["Phường 1", "Phường 2", "Phường 10", "Phường 8", "Phường 9"],
      "Thành phố Bảo Lộc": ["Phường 1", "Phường 2", "Phường B'Lao", "Phường Lộc Tiến"],
      "Thành phố Gia Nghĩa": ["Phường Nghĩa Đức", "Phường Nghĩa Thành", "Phường Nghĩa Trung", "Phường Nghĩa Phú"],
      "Thành phố Phan Thiết": ["Phường Đức Nghĩa", "Phường Mũi Né", "Phường Lạc Đạo", "Phường Phú Thủy"],
      "Huyện Đức Trọng": ["Thị trấn Liên Nghĩa", "Xã Hiệp Thạnh", "Xã Liên Đầm"],
      "Huyện Tuy Phong": ["Thị trấn Liên Hương", "Thị trấn Phan Rí Cửa", "Xã Chí Công"],
    },
    "Tỉnh Đồng Nai": {
      "Thành phố Biên Hòa": ["Phường Thanh Bình", "Phường Quyết Thắng", "Phường Tân Phong", "Phường Trảng Dài", "Phường Hố Nai"],
      "Thành phố Long Khánh": ["Phường Xuân Trung", "Phường Xuân An", "Phường Xuân Bình"],
      "Thành phố Đồng Xoài": ["Phường Tân Bình", "Phường Tân Xuân", "Phường Tân Phú", "Phường Tân Đồng"],
      "Thị xã Bình Long": ["Phường An Lộc", "Phường Hưng Chiến", "Phường Phú Thịnh"],
      "Huyện Long Thành": ["Thị trấn Long Thành", "Xã Lộc An", "Xã Bình Sơn"],
    },
    "Tỉnh Tây Ninh": {
      "Thành phố Tây Ninh": ["Phường 1", "Phường 2", "Phường 3", "Phường Hiệp Ninh"],
      "Thành phố Tân An": ["Phường 1", "Phường 2", "Phường 3", "Phường 4", "Phường Khánh Hậu"],
      "Thị xã Trảng Bàng": ["Phường Trảng Bàng", "Phường Gia Lộc", "Phường An Tịnh"],
      "Huyện Đức Hòa": ["Thị trấn Hậu Nghĩa", "Thị trấn Đức Hòa", "Xã Mỹ Hạnh Nam"],
    },
    "Tỉnh Vĩnh Long": {
      "Thành phố Vĩnh Long": ["Phường 1", "Phường 2", "Phường 4", "Phường 8", "Phường 9"],
      "Thành phố Bến Tre": ["Phường An Hội", "Phường Phú Khương", "Phường Phú Tân", "Phường 8"],
      "Thành phố Trà Vinh": ["Phường 1", "Phường 2", "Phường 5", "Phường 6"],
      "Huyện Long Hồ": ["Thị trấn Long Hồ", "Xã Thanh Đức", "Xã Long An"],
      "Huyện Châu Thành": ["Thị trấn Châu Thành", "Xã Hữu Định", "Xã An Khánh"],
    },
    "Tỉnh Đồng Tháp": {
      "Thành phố Cao Lãnh": ["Phường 1", "Phường 2", "Phường Mỹ Phú", "Phường Hòa Thuận"],
      "Thành phố Sa Đéc": ["Phường 1", "Phường 2", "Phường An Hòa", "Phường Tân Quy Đông"],
      "Thành phố Mỹ Tho": ["Phường 1", "Phường 2", "Phường 5", "Phường 7", "Phường Tân Long"],
      "Thị xã Gò Công": ["Phường 1", "Phường 2", "Phường Long Thuận"],
      "Huyện Cao Lãnh": ["Thị trấn Mỹ Thọ", "Xã Mỹ Hội", "Xã Bình Hàng Tây"],
    },
    "Tỉnh Cà Mau": {
      "Thành phố Cà Mau": ["Phường 1", "Phường 2", "Phường 5", "Phường 8", "Phường 9"],
      "Thành phố Bạc Liêu": ["Phường 1", "Phường 2", "Phường 3", "Phường 5", "Phường Nhà Mát"],
      "Huyện Trần Văn Thời": ["Thị trấn Trần Văn Thời", "Thị trấn Sông Đốc", "Xã Khánh Lộc"],
      "Huyện Giá Rai": ["Phường 1", "Phường Hộ Phòng", "Xã Phong Thạnh Đông"],
    },
    "Tỉnh An Giang": {
      "Thành phố Long Xuyên": ["Phường Mỹ Long", "Phường Đông Xuyên", "Phường Mỹ Phước", "Phường Mỹ Quý", "Phường Bình Đức"],
      "Thành phố Châu Đốc": ["Phường Châu Phú A", "Phường Châu Phú B", "Phường Núi Sam"],
      "Thành phố Rạch Giá": ["Phường Vĩnh Thanh Vân", "Phường An Hòa", "Phường Rạch Sỏi", "Phường Vĩnh Lạc"],
      "Thành phố Phú Quốc": ["Phường Dương Đông", "Phường An Thới", "Xã Hàm Ninh"],
      "Huyện Thoại Sơn": ["Thị trấn Núi Sập", "Thị trấn Phú Hòa", "Xã Thoại Giang"],
    },
  };
}
